# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
