#!/usr/bin/python
# -*- coding: utf-8 -*-


FEBRABAN_V10_7 = {
    "trailer": {
        "opcional": False,
        "campos": {
            "01.9": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "code": "G001",
            },
            "02.9": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": "9999",
                "code": "G002",
            },
            "03.9": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "9",
                "code": "G003",
            },
            "04.9": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 9,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
            "05.9": {
                "name": "Quantidade de Lotes do Arquivo",
                "posicao_inicio": 18,
                "posicao_fim": 23,
                "formato": "num",
                "default": None,
                "code": "G049",
            },
            "06.9": {
                "name": "Quantidade de Registros do Arquivo",
                "posicao_inicio": 24,
                "posicao_fim": 29,
                "formato": "num",
                "default": None,
                "code": "G056",
            },
            "07.9": {
                "name": "Qtde de Contas p/ Conc. (Lotes)",
                "posicao_inicio": 30,
                "posicao_fim": 35,
                "formato": "num",
                "default": None,
                "code": "G037",
            },
            "08.9": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 36,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
        }
    },
    "trailer_lote": {
        "opcional": False,
        "campos": {
            "01.5": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "code": "G001",
            },
            "02.5": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": None,
                "code": "G002",
            },
            "03.5": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "5",
                "code": "G003",
            },
            "04.5": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 9,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
            "05.5": {
                "name": "Quantidade de Registros do Lote",
                "posicao_inicio": 18,
                "posicao_fim": 23,
                "formato": "num",
                "default": None,
                "code": "G057",
            },
            "06.5": {
                "name": "Somatória dos Valores",
                "posicao_inicio": 24,
                "posicao_fim": 41,
                "formato": "num",
                "default": None,
                "code": "P007",
            },
            "07.5": {
                "name": "Somatória de Quantidade de Moedas",
                "posicao_inicio": 42,
                "posicao_fim": 59,
                "formato": "num",
                "default": None,
                "code": "G058",
            },
            "08.5": {
                "name": "Número Aviso de Débito ",
                "posicao_inicio": 60,
                "posicao_fim": 65,
                "formato": "alfa",
                "default": None,
                "code": "G066",
            },
            "09.5": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 66,
                "posicao_fim": 230,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
            "10.5": {
                "name": "Códigos das Ocorrências para Retorno",
                "posicao_inicio": 231,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": None,
                "code": "G059",
            },
        }
    },
    "lote_detalhe_segmento_c": {
        "opcional": True,
        "campos": {
            "01.3C": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "code": "G001",
            },
            "02.3C": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": None,
                "code": "G002",
            },
            "03.3C": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "3",
                "code": "G003",
            },
            "04.3C": {
                "name": "Nº Seqüencial do Registro no Lote",
                "posicao_inicio": 9,
                "posicao_fim": 13,
                "formato": "num",
                "default": "3",
                "code": "G038",
            },
            "05.3C": {
                "name": "Código de Segmento do Reg. Detalhe",
                "posicao_inicio": 14,
                "posicao_fim": 14,
                "formato": "alfa",
                "default": "C",
                "code": "G039",
            },
            "06.3C": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 15,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
            "07.3C": {
                "name": "Valor do IR",
                "posicao_inicio": 18,
                "posicao_fim": 32,
                "formato": "num",
                "default": None,
                "code": "G050",
            },
            "08.3C": {
                "name": "Valor do ISS",
                "posicao_inicio": 33,
                "posicao_fim": 47,
                "formato": "num",
                "default": None,
                "code": "G051",
            },
            "09.3C": {
                "name": "Valor do IOF",
                "posicao_inicio": 48,
                "posicao_fim": 62,
                "formato": "num",
                "default": None,
                "code": "G052",
            },
            "10.3C": {
                "name": "Valor Outras Deduções",
                "posicao_inicio": 63,
                "posicao_fim": 77,
                "formato": "num",
                "default": None,
                "code": "G053",
            },
            "11.3C": {
                "name": "Valor Outras Acréscimos",
                "posicao_inicio": 78,
                "posicao_fim": 92,
                "formato": "num",
                "default": None,
                "code": "G054",
            },
            "12.3C": {
                "name": "Agência do Favorecido",
                "posicao_inicio": 93,
                "posicao_fim": 97,
                "formato": "num",
                "default": None,
                "code": "G008",
            },
            "13.3C": {
                "name": "Dígito Verificador da Agência",
                "posicao_inicio": 98,
                "posicao_fim": 98,
                "formato": "alfa",
                "default": None,
                "code": "G009",
            },
            "14.3C": {
                "name": "Número Conta Corrente",
                "posicao_inicio": 99,
                "posicao_fim": 110,
                "formato": "num",
                "default": None,
                "code": "G010",
            },
            "15.3C": {
                "name": "Dígito Verificador da Conta",
                "posicao_inicio": 111,
                "posicao_fim": 111,
                "formato": "alfa",
                "default": None,
                "code": "G011",
            },
            "16.3C": {
                "name": "Dígito Verificador Agência/Conta",
                "posicao_inicio": 112,
                "posicao_fim": 112,
                "formato": "alfa",
                "default": None,
                "code": "G012",
            },
            "17.3C": {
                "name": "Valor do INSS",
                "posicao_inicio": 113,
                "posicao_fim": 127,
                "formato": "num",
                "default": None,
                "code": "G055",
            },
            "18.3C": {
                "name": "Número Conta Pagamento Creditada",
                "posicao_inicio": 128,
                "posicao_fim": 147,
                "formato": "num",
                "default": None,
                "code": "P016",
            },
            "19.3C": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 148,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
        }
    },
    "lote_detalhe_segmento_b": {
        "opcional": False,
        "campos": {
            "01.3B": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "code": "G001",
            },
            "02.3B": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": None,
                "code": "G002",
            },
            "03.3B": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "3",
                "code": "G003",
            },
            "04.3B": {
                "name": "Nº Seqüencial do Registro no Lote",
                "posicao_inicio": 9,
                "posicao_fim": 13,
                "formato": "num",
                "default": "3",
                "code": "G038",
            },
            "05.3B": {
                "name": "Código de Segmento do Reg. Detalhe",
                "posicao_inicio": 14,
                "posicao_fim": 14,
                "formato": "alfa",
                "default": "B",
                "code": "G039",
            },
            "06.3B": {
                "name": "Forma de Iniciação",
                "posicao_inicio": 15,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": None,
                "code": "G100",
            },
            "07.3B": {
                "name": "Tipo de Inscrição do Favorecido",
                "posicao_inicio": 18,
                "posicao_fim": 18,
                "formato": "num",
                "default": None,
                "code": "G005",
            },
            "08.3B": {
                "name": "Nº de Inscrição do Favorecido",
                "posicao_inicio": 19,
                "posicao_fim": 32,
                "formato": "num",
                "default": None,
                "code": "G006",
            },
            "09.3B": {
                "name": "Informação 10",
                "posicao_inicio": 33,
                "posicao_fim": 67,
                "formato": "alfa",
                "default": None,
                "code": "G101",
            },
            "10.3B": {
                "name": "Informação 11",
                "posicao_inicio": 68,
                "posicao_fim": 127,
                "formato": "alfa",
                "default": None,
                "code": "G101",
            },
            "11.3B": {
                "name": "Informação 12",
                "posicao_inicio": 128,
                "posicao_fim": 226,
                "formato": "alfa",
                "default": None,
                "code": "G101",
            },
            "12.3B": {
                "name": "Uso Exclusivo para o SIAPE",
                "posicao_inicio": 227,
                "posicao_fim": 232,
                "formato": "num",
                "default": None,
                "code": "P012",
            },
            "13.3B": {
                "name": "Código ISPB",
                "posicao_inicio": 233,
                "posicao_fim": 240,
                "formato": "num",
                "default": None,
                "code": "P015",
            },
        }
    },
    "lote_detalhe_segmento_a": {
        "opcional": False,
        "campos": {
            "01.3A": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "code": "G001",
            },
            "02.3A": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": None,
                "code": "G002",
            },
            "03.3A": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "3",
                "code": "G003",
            },
            "04.3A": {
                "name": "Nº Seqüencial do Registro no Lote",
                "posicao_inicio": 9,
                "posicao_fim": 13,
                "formato": "num",
                "default": None,
                "code": "G038",
            },
            "05.3A": {
                "name": "Código de Segmento do Reg. Detalhe",
                "posicao_inicio": 14,
                "posicao_fim": 14,
                "formato": "alfa",
                "default": "A",
                "code": "G039",
            },
            "06.3A": {
                "name": "Tipo de Movimento",
                "posicao_inicio": 15,
                "posicao_fim": 15,
                "formato": "num",
                "default": None,
                "code": "G060",
            },
            "07.3A": {
                "name": "Código da Instrução p/ Movimento",
                "posicao_inicio": 16,
                "posicao_fim": 17,
                "formato": "num",
                "default": None,
                "code": "G061",
            },
            "08.3A": {
                "name": "Código da Câmara Centralizadora",
                "posicao_inicio": 18,
                "posicao_fim": 20,
                "formato": "num",
                "default": None,
                "code": "P001",
            },
            "09.3A": {
                "name": "Código do Banco do Favorecido",
                "posicao_inicio": 21,
                "posicao_fim": 23,
                "formato": "num",
                "default": None,
                "code": "P002",
            },
            "10.3A": {
                "name": "Ag. Mantenedora da Cta do Favor.",
                "posicao_inicio": 24,
                "posicao_fim": 28,
                "formato": "num",
                "default": None,
                "code": "G008",
            },
            "11.3A": {
                "name": "Dígito Verificador da Agência",
                "posicao_inicio": 29,
                "posicao_fim": 29,
                "formato": "alfa",
                "default": None,
                "code": "G009",
            },
            "12.3A": {
                "name": "Número da Conta Corrente",
                "posicao_inicio": 30,
                "posicao_fim": 41,
                "formato": "num",
                "default": None,
                "code": "G010",
            },
            "13.3A": {
                "name": "Dígito Verificador da Conta",
                "posicao_inicio": 42,
                "posicao_fim": 42,
                "formato": "alfa",
                "default": None,
                "code": "G011",
            },
            "14.3A": {
                "name": "Dígito Verificador da AG/Conta",
                "posicao_inicio": 43,
                "posicao_fim": 43,
                "formato": "alfa",
                "default": None,
                "code": "G012",
            },
            "15.3A": {
                "name": "Nome do Favorecido",
                "posicao_inicio": 44,
                "posicao_fim": 73,
                "formato": "alfa",
                "default": None,
                "code": "G013",
            },
            "16.3A": {
                "name": "Nº do Docum. Atribuído p/ Empresa",
                "posicao_inicio": 74,
                "posicao_fim": 93,
                "formato": "alfa",
                "default": None,
                "code": "G064",
            },
            "17.3A": {
                "name": "Data do Pagamento",
                "posicao_inicio": 94,
                "posicao_fim": 101,
                "formato": "num",
                "default": None,
                "code": "P009",
            },
            "18.3A": {
                "name": "Tipo da Moeda",
                "posicao_inicio": 102,
                "posicao_fim": 104,
                "formato": "num",
                "default": None,
                "code": "G040",
            },
            "19.3A": {
                "name": "Quantidade da Moeda",
                "posicao_inicio": 105,
                "posicao_fim": 119,
                "formato": "num",
                "default": None,
                "code": "G041",
            },
            "20.3A": {
                "name": "Valor do Pagamento",
                "posicao_inicio": 120,
                "posicao_fim": 134,
                "formato": "num",
                "default": None,
                "code": "P010",
            },
            "21.3A": {
                "name": "Nº do Docum. Atribuído pelo Banco",
                "posicao_inicio": 135,
                "posicao_fim": 154,
                "formato": "alfa",
                "default": None,
                "code": "G043",
            },
            "22.3A": {
                "name": "Data Real da Efetivação Pagto",
                "posicao_inicio": 155,
                "posicao_fim": 162,
                "formato": "num",
                "default": None,
                "code": "P003",
            },
            "23.3A": {
                "name": "Valor Real da Efetivação do Pagto",
                "posicao_inicio": 163,
                "posicao_fim": 177,
                "formato": "num",
                "default": None,
                "code": "P004",
            },
            "24.3A": {
                "name": "Outras Informações",
                "posicao_inicio": 178,
                "posicao_fim": 217,
                "formato": "alfa",
                "default": None,
                "code": "G031",
            },
            "25.3A": {
                "name": "Compl. Tipo Serviço",
                "posicao_inicio": 218,
                "posicao_fim": 219,
                "formato": "alfa",
                "default": None,
                "code": "P005",
            },
            "26.3A": {
                "name": "Codigo finalidade da TED",
                "posicao_inicio": 220,
                "posicao_fim": 224,
                "formato": "alfa",
                "default": None,
                "code": "P011",
            },
            "27.3A": {
                "name": "Complemento de finalidade pagto.",
                "posicao_inicio": 225,
                "posicao_fim": 226,
                "formato": "alfa",
                "default": None,
                "code": "P013",
            },
            "28.3A": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 227,
                "posicao_fim": 229,
                "formato": "alfa",
                "default": None,
                "code": "G004",
            },
            "29.3A": {
                "name": "Aviso ao Favorecido",
                "posicao_inicio": 230,
                "posicao_fim": 230,
                "formato": "num",
                "default": None,
                "code": "P006",
            },
            "30.3A": {
                "name": "Códigos das Ocorrências para Retorno",
                "posicao_inicio": 231,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": None,
                "code": "G059",
            },
        }
    },
    # Pagamento Através de Crédito em Conta, Cheque, OP, DOC, TED ou Pagamento com Autenticação
    "header_lote": {
        "opcional": False,
        "campos": {
            "01.1": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "descricao": "G001",
            },
            "02.1": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": None,
                "descricao": "G002",
            },
            "03.1": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "1",
                "descricao": "G003",
            },
            "04.1": {
                "name": "Tipo da Operação",
                "posicao_inicio": 9,
                "posicao_fim": 9,
                "formato": "alfa",
                "default": "C",
                "descricao": "G028",
            },
            "05.1": {
                "name": "Tipo do Serviço",
                "posicao_inicio": 10,
                "posicao_fim": 11,
                "formato": "num",
                "default": None,
                "descricao": "G025",
            },
            "06.1": {
                "name": "Forma de Lançamento",
                "posicao_inicio": 12,
                "posicao_fim": 13,
                "formato": "num",
                "default": None,
                "descricao": "G029",
            },
            "07.1": {
                "name": "Nº da Versão do Layout do Lote",
                "posicao_inicio": 14,
                "posicao_fim": 16,
                "formato": "num",
                "default": "046",
                "descricao": "G030",
            },
            "08.1": {
                "name": "Uso Exclusivo da FEBRABAN/CNAB",
                "posicao_inicio": 17,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": "Brancos",
                "descricao": "G004",
            },
            "09.1": {
                "name": "Tipo de Inscrição da Empresa",
                "posicao_inicio": 18,
                "posicao_fim": 18,
                "formato": "num",
                "default": None,
                "descricao": "G005",
            },
            "10.1": {
                "name": "Número de Inscrição da Empresa",
                "posicao_inicio": 19,
                "posicao_fim": 32,
                "formato": "num",
                "default": None,
                "descricao": "G006",
            },
            "11.1": {
                "name": "Código do Convênio no Banco",
                "posicao_inicio": 33,
                "posicao_fim": 52,
                "formato": "alfa",
                "default": None,
                "descricao": "G007",
            },
            "12.1": {
                "name": "Agência Mantenedora da Conta",
                "posicao_inicio": 53,
                "posicao_fim": 57,
                "formato": "num",
                "default": None,
                "descricao": "G008",
            },
            "13.1": {
                "name": "Dígito Verificador da Agência",
                "posicao_inicio": 58,
                "posicao_fim": 58,
                "formato": "alfa",
                "default": None,
                "descricao": "G009",
            },
            "14.1": {
                "name": "Número da Conta Corrente",
                "posicao_inicio": 59,
                "posicao_fim": 70,
                "formato": "num",
                "default": None,
                "descricao": "G010",
            },
            "15.1": {
                "name": "Dígito Verificador da Conta",
                "posicao_inicio": 71,
                "posicao_fim": 71,
                "formato": "alfa",
                "default": "Brancos",
                "descricao": "G011",
            },
            "16.1": {
                "name": "Dígito Verificador da Ag/Conta",
                "posicao_inicio": 72,
                "posicao_fim": 72,
                "formato": "alfa",
                "default": None,
                "descricao": "G012",
            },
            "17.1": {
                "name": "Nome da Empresa",
                "posicao_inicio": 73,
                "posicao_fim": 102,
                "formato": "alfa",
                "default": None,
                "descricao": "G013",
            },
            "18.1": {
                "name": "Mensagem",
                "posicao_inicio": 103,
                "posicao_fim": 142,
                "formato": "alfa",
                "default": None,
                "descricao": "G031",
            },
            "19.1": {
                "name": "Nome da Rua, Av, Pça, Etc",
                "posicao_inicio": 143,
                "posicao_fim": 172,
                "formato": "alfa",
                "default": None,
                "descricao": "G032",
            },
            "20.1": {
                "name": "Número do Local",
                "posicao_inicio": 173,
                "posicao_fim": 177,
                "formato": "num",
                "default": "103",
                "descricao": "G032",
            },
            "21.1": {
                "name": "Casa, Apto, Sala, Etc",
                "posicao_inicio": 178,
                "posicao_fim": 192,
                "formato": "alfa",
                "default": None,
                "descricao": "G032",
            },
            "22.1": {
                "name": "Nome da Cidade",
                "posicao_inicio": 193,
                "posicao_fim": 212,
                "formato": "alfa",
                "default": None,
                "descricao": "G033",
            },
            "23.1": {
                "name": "CEP",
                "posicao_inicio": 213,
                "posicao_fim": 217,
                "formato": "num",
                "default": None,
                "descricao": "G034",
            },
            "24.1": {
                "name": "Complemento do CEP",
                "posicao_inicio": 218,
                "posicao_fim": 220,
                "formato": "alfa",
                "default": None,
                "descricao": "G035",
            },
            "25.1": {
                "name": "Sigla do Estado",
                "posicao_inicio": 221,
                "posicao_fim": 222,
                "formato": "alfa",
                "default": None,
                "descricao": "G036",
            },
            "26.1": {
                "name": "Indicativo da Forma de Pagamento do Serviço",
                "posicao_inicio": 223,
                "posicao_fim": 224,
                "formato": "num",
                "default": None,
                "descricao": "P014",
            },
            "27.1": {
                "name": "Uso Exclusivo FEBRABAN/CNAB",
                "posicao_inicio": 225,
                "posicao_fim": 230,
                "formato": "alfa",
                "default": None,
                "descricao": "G004",
            },
            "28.1": {
                "name": "Códigos das Ocorrências p/ Retorno",
                "posicao_inicio": 231,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": None,
                "descricao": "G059",
            },
        }
    },
    "header": {
        "opcional": False,
        "campos": {
            "01.0": {
                "name": "Código do Banco na Compensação",
                "posicao_inicio": 1,
                "posicao_fim": 3,
                "formato": "num",
                "default": None,
                "descricao": "G001",
            },
            "02.0": {
                "name": "Lote de Serviço",
                "posicao_inicio": 4,
                "posicao_fim": 7,
                "formato": "num",
                "default": "0000",
                "descricao": "G002",
            },
            "03.0": {
                "name": "Tipo de Registro",
                "posicao_inicio": 8,
                "posicao_fim": 8,
                "formato": "num",
                "default": "0",
                "descricao": "G003",
            },
            "04.0": {
                "name": "Uso Exclusivo FEBRABAN / CNAB",
                "posicao_inicio": 9,
                "posicao_fim": 17,
                "formato": "alfa",
                "default": "Brancos",
                "descricao": "G004",
            },
            "05.0": {
                "name": "Tipo de Inscrição da Empresa",
                "posicao_inicio": 18,
                "posicao_fim": 18,
                "formato": "num",
                "default": None,
                "descricao": "G005",
            },
            "06.0": {
                "name": "Número de Inscrição da Empresa",
                "posicao_inicio": 19,
                "posicao_fim": 32,
                "formato": "num",
                "default": None,
                "descricao": "G006",
            },
            "07.0": {
                "name": "Código do Convênio no Banco",
                "posicao_inicio": 33,
                "posicao_fim": 52,
                "formato": "alfa",
                "default": None,
                "descricao": "G007",
            },
            "08.0": {
                "name": "Agência Mantenedora da Conta",
                "posicao_inicio": 53,
                "posicao_fim": 57,
                "formato": "num",
                "default": None,
                "descricao": "G008",
            },
            "09.0": {
                "name": "Dígito Verificador da Agência",
                "posicao_inicio": 58,
                "posicao_fim": 58,
                "formato": "alfa",
                "default": None,
                "descricao": "G009",
            },
            "10.0": {
                "name": "Número da Conta Corrente",
                "posicao_inicio": 59,
                "posicao_fim": 70,
                "formato": "num",
                "default": None,
                "descricao": "G010",
            },
            "11.0": {
                "name": "Dígito Verificador da Conta",
                "posicao_inicio": 71,
                "posicao_fim": 71,
                "formato": "alfa",
                "default": None,
                "descricao": "G011",
            },
            "12.0": {
                "name": "Dígito Verificador da Ag/Conta",
                "posicao_inicio": 72,
                "posicao_fim": 72,
                "formato": "alfa",
                "default": None,
                "descricao": "G012",
            },
            "13.0": {
                "name": "Nome da Empresa",
                "posicao_inicio": 73,
                "posicao_fim": 102,
                "formato": "alfa",
                "default": None,
                "descricao": "G013",
            },
            "14.0": {
                "name": "Nome do Banco",
                "posicao_inicio": 103,
                "posicao_fim": 132,
                "formato": "alfa",
                "default": None,
                "descricao": "G014",
            },
            "15.0": {
                "name": "Uso Exclusivo FEBRABAN / CNAB",
                "posicao_inicio": 133,
                "posicao_fim": 142,
                "formato": "alfa",
                "default": "Brancos",
                "descricao": "G004",
            },
            "16.0": {
                "name": "Código Remessa / Retorno",
                "posicao_inicio": 143,
                "posicao_fim": 143,
                "formato": "num",
                "default": None,
                "descricao": "G015",
            },
            "17.0": {
                "name": "Data de Geração do Arquivo",
                "posicao_inicio": 144,
                "posicao_fim": 151,
                "formato": "num",
                "default": None,
                "descricao": "G016",
            },
            "18.0": {
                "name": "Hora de Geração do Arquivo",
                "posicao_inicio": 152,
                "posicao_fim": 157,
                "formato": "num",
                "default": None,
                "descricao": "G017",
            },
            "19.0": {
                "name": "Número Seqüencial do Arquivo",
                "posicao_inicio": 158,
                "posicao_fim": 163,
                "formato": "num",
                "default": None,
                "descricao": "G018",
            },
            "20.0": {
                "name": "Número da Versão do Layout do Arquivo",
                "posicao_inicio": 164,
                "posicao_fim": 166,
                "formato": "num",
                "default": "103",
                "descricao": "G019",
            },
            "21.0": {
                "name": "Densidade de Gravação do Arquivo",
                "posicao_inicio": 167,
                "posicao_fim": 171,
                "formato": "num",
                "default": None,
                "descricao": "G020",
            },
            "22.0": {
                "name": "Para Uso Reservado do Banco",
                "posicao_inicio": 172,
                "posicao_fim": 191,
                "formato": "alfa",
                "default": None,
                "descricao": "G021",
            },
            "23.0": {
                "name": "Para Uso Reservado da Empresa",
                "posicao_inicio": 192,
                "posicao_fim": 211,
                "formato": "alfa",
                "default": None,
                "descricao": "G022",
            },
            "24.0": {
                "name": "Uso Exclusivo FEBRABAN / CNAB",
                "posicao_inicio": 212,
                "posicao_fim": 240,
                "formato": "alfa",
                "default": "Brancos",
                "descricao": "G004",
            },
        }
    },
}
