name: CI

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-cov
          pip install -r requirements.txt && pip install -r dev-requirements.txt

      - name: Run prospector
        run: prospector --messages-only

      - name: Run isort
        run: isort **/*.py --check-only
      
      - name: Run black
        run: black . --check --diff

      - name: Run bandit
        run: bandit -r . 

      - name: Run Tests
        run: python -m pytest --cov-report=html ./tests
