name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Install coveralls
        run: pip install coveralls==3.0.0

      - name: Run prospector
        run: poetry run prospector --messages-only

      - name: Run isort
        run: poetry run isort **/*.py --check-only

      - name: Run black
        run: poetry run black . --check --diff

      - name: Run bandit
        run: poetry run bandit -r . -x ./.venv

      - name: Run Tests
        run: poetry run pytest --cov-report xml --cov=cnab,providers,tests tests/

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v2
        with:
          name: pytest-gh-actions-coverage
          path: coverage.xml
          if-no-files-found: error

      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
